application: poised-shuttle-119914
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: admin.php

- url: /checklogin.php
  script: checklogin.php

- url: /admin.php
  script: admin.php

- url: /adminhistory.php
  script: adminhistory.php

- url: /adminhistory2.php
  script: adminhistory2.php


- url: /logout.php
  script: /logout.php

- url: /guideline.php
  script: /guideline.php

- url: /js
  static_dir: js

- url: /bootstrap
  static_dir: bootstrap

- url: /index.php
  script: index.php

- url: /lib
  static_dir: lib


